name: "Build Docker Image"
description: "Build a Docker Image and push it to the given registry"
inputs:
  directory:
    description: "The folder that contains the Dockerfile and all that's needed to build the image"
    required: true
  image_name:
    description: "The name of the image to build"
    required: true
  image_registry:
    description: "The registry the image should be pushed to"
    required: true
  namespaced_image_registry:
    description: "The namespaced registry the image should be pushed to"
    required: true
  image_registry_username:
    description: "The username of the repository for the image"
    required: true
  image_registry_password:
    description: "The password for the image repository"
    required: true
  image_description:
    description: "A description of the image being built"
    required: true
  tags:
    description: "A multi-line string that can be passed to the docker/metadata-action"
    required: true
  platforms:
    description: "A comma separated list of the platforms to build for"
    required: true

runs:
  using: composite
  steps:
    - name: Log in to the Container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      with:
        registry: ${{ inputs.image_registry }}
        username: ${{ inputs.image_registry_username }}
        password: ${{ inputs.image_registry_password }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@941183f0a080fa6be59a9e3d3f4108c19a528204
    - name: Get Docker Metadata
      id: meta
      uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
      env:
        DOCKER_METADATA_PR_HEAD_SHA: true
      with:
        images: ${{ inputs.namespaced_image_registry }}/${{ inputs.image_name }}
        tags: ${{ inputs.tags }}
        labels: |
          org.opencontainers.image.title=${{ inputs.image_name }}
          org.opencontainers.image.description=${{ inputs.image_description }}
          org.opencontainers.image.vendor=Apollo GraphQL
          org.opencontainers.image.licenses=MIT
        annotations: |
          org.opencontainers.image.title=${{ inputs.image_name }}
          org.opencontainers.image.description=${{ inputs.description }}
          org.opencontainers.image.vendor=Apollo GraphQL
          org.opencontainers.image.licenses=MIT
    - name: Build and Push Docker image
      id: push
      uses: docker/build-push-action@67dc78bbaf388b3265f7e1c880e681f4b90d5f48
      with:
        context: ${{ inputs.directory }}
        file: ${{ inputs.directory }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        annotations: ${{ steps.meta.outputs.annotations }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}