name: Build & Publish Changed Docker Images

on:
  push:
    branches: ['main']
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  calculate-images-to-build:
    name: Calculate Images To Build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build_matrix.outputs.matrix }}
      has_changes: ${{ steps.build_matrix.outputs.has_changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Calculate changed files directories
        id: calculate_changed_files
        uses: tj-actions/changed-files@abdd2f68ea150cee8f236d4a9fb4e0f2491abf1b
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          json: true
          escape_json: false
      - name: Build image matrix
        id: build_matrix
        env:
          CHANGED_FILES: ${{ steps.calculate_changed_files.outputs.all_changed_files }}
        run: |
          MATRIX=$(./.github/scripts/build_image_matrix.sh "$CHANGED_FILES" --tags=versioned)
          echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"
          if [ "$(echo "$MATRIX" | jq 'length')" -gt 0 ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

  pipeline:
    name: Image Pipeline
    needs: calculate-images-to-build
    if: needs.calculate-images-to-build.outputs.has_changes == 'true'
    uses: ./.github/workflows/_image_pipeline.yml
    with:
      matrix: ${{ needs.calculate-images-to-build.outputs.matrix }}
      do_release: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    secrets: inherit

  check-builds-all-completes:
    name: Docker Images Built & Pushed
    if: ${{ always() }}
    needs: [calculate-images-to-build, pipeline]
    runs-on: ubuntu-latest
    steps:
      - run: |
          exit ${{ (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) && 1 || 0 }}