on:
  workflow_call:
    inputs:
      config_yaml_path:
        type: string
        required: true
        description: "The path to the config.yaml file in the repo"
    outputs:
      current_version: ${{ steps.extract_from_config_yaml.outputs.current_version }}
      platforms: ${{ steps.extract_from_config_yaml.outputs.platforms }}
      description: ${{ steps.extract_from_config_yaml.outputs.description }}

jobs:

  extract_details_from_config_yaml:
    name: "Extract Details From config.yaml"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: Extract Details From config.yml
        id: extract_from_config_yaml
        run: |
          echo "current_version=$(cat ${{ inputs.config_yaml_path }} | yq '.version')" >> "$GITHUB_OUTPUT"
          echo "platforms=$(cat ${{ inputs.config_yaml_path }} | yq '.platforms | join(",")')" >> "$GITHUB_OUTPUT"
          echo "description=$(cat ${{ inputs.config_yaml_path }} | yq '.description')" >> "$GITHUB_OUTPUT"